spring:
  cloud:
    gateway:
      routes:
      - id: nameRoot
        uri: lb://name123
        predicates:
        - Path=/name123/**
        filters:
        - RewritePath=/name(?<segment>.*), $\{segment}
      - id: greeting
        uri: lb://greet123
        predicates:
        - Path=/greet123/**
        filters:
        - RewritePath=/greeting(?<segment>.*), $\{segment}
